version: "3"

services:
 core:
    image: nginx
    container_name: core.hoster
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

      - /etc/letsencrypt/live/inventory.sharp.freshtuna/fullchain.pem:/etc/letsencrypt/live/inventory.sharp.freshtuna/fullchain.pem
      - /etc/letsencrypt/live/inventory.sharp.freshtuna/privkey.pem:/etc/letsencrypt/live/inventory.sharp.freshtuna/privkey.pem

      - /etc/letsencrypt/live/turtle.freshtuna/fullchain.pem:/etc/letsencrypt/live/turtle.freshtuna/fullchain.pem
      - /etc/letsencrypt/live/turtle.freshtuna/privkey.pem:/etc/letsencrypt/live/turtle.freshtuna/privkey.pem

      - /var/www/letsencrypt:/var/www/letsencrypt
    networks:
      - hoster
      - sharp
      - turtle
    ports:
      - "443:443"
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

networks:
  hoster:
  turtle:
    external: true
  sharp:
    external: true

